# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.1"

services:
    php:
        build: .
        ports:
                - "80:80"
                - "443:443"
        volumes:
                - "./www:/var/www/html"
        links:
                - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
                - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
                - ./mysql:/docker-entrypoint-initdb.d
                - ./mysql/config:/etc/mysql/conf.d
                - ./database:/var/lib/mysql
        environment:
                #- MYSQL_USER=admin
                #- MYSQL_PASSWORD=admin
                - MYSQL_ROOT_PASSWORD=root
                - MYSQL_DATABASE=banco_bd
        networks:
            - default
